// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Different types of approval workflows that can be used to gate privileged
/// access granting.
public struct ApprovalWorkflow: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  public var approvalWorkflow: OneOf_ApprovalWorkflow? = nil

  /// Initialize a new instance of `ApprovalWorkflow`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ApprovalWorkflow().with { $0.manualApprovals = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case manualApprovals = "manualApprovals"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var approvalWorkflow: OneOf_ApprovalWorkflow? = nil
    let approvalWorkflowCheckAndSet = {
      if approvalWorkflow != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'approvalWorkflow'"))
      }
      approvalWorkflow = $0
    }
    if let manualApprovals = try container.decodeIfPresent(
      ManualApprovals?.self, forKey: .manualApprovals)
    {
      try approvalWorkflowCheckAndSet(.manualApprovals(manualApprovals))
    }
    self.approvalWorkflow = approvalWorkflow
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.approvalWorkflow {
      switch choice {
      case .manualApprovals(let value):
        try container.encode(value, forKey: .manualApprovals)
      }
    }
  }

  public enum OneOf_ApprovalWorkflow: Codable, Equatable, Sendable {
    /// An approval workflow where users designated as approvers review and act
    /// on the grants.
    indirect case manualApprovals(ManualApprovals?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.ApprovalWorkflow"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
