// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Response message for `CheckOnboardingStatus` method.
public struct CheckOnboardingStatusResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The service account that PAM uses to act on this resource.
  public var serviceAccount: Swift.String = Swift.String()

  /// List of issues that are preventing PAM from functioning for this resource
  /// and need to be fixed to complete onboarding. Some issues might not be
  /// detected or reported.
  public var findings: [CheckOnboardingStatusResponse.Finding] = []

  /// Initialize a new instance of `CheckOnboardingStatusResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CheckOnboardingStatusResponse().with { $0.serviceAccount = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Finding represents an issue which prevents PAM from functioning properly
  /// for this resource.
  public struct Finding: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    public var findingType: OneOf_FindingType? = nil

    /// Initialize a new instance of `Finding`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Finding().with { $0.iamAccessDenied = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case iamAccessDenied = "iamAccessDenied"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var findingType: OneOf_FindingType? = nil
      let findingTypeCheckAndSet = {
        if findingType != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'findingType'"))
        }
        findingType = $0
      }
      if let iamAccessDenied = try container.decodeIfPresent(
        CheckOnboardingStatusResponse.Finding.IAMAccessDenied?.self, forKey: .iamAccessDenied)
      {
        try findingTypeCheckAndSet(.iamAccessDenied(iamAccessDenied))
      }
      self.findingType = findingType
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.findingType {
        switch choice {
        case .iamAccessDenied(let value):
          try container.encode(value, forKey: .iamAccessDenied)
        }
      }
    }

    /// PAM's service account is being denied access by Cloud IAM.
    /// This can be fixed by granting a role that contains the missing
    /// permissions to the service account or exempting it from deny policies if
    /// they are blocking the access.
    public struct IAMAccessDenied: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// List of permissions that are being denied.
      public var missingPermissions: [Swift.String] = []

      /// Initialize a new instance of `IAMAccessDenied`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = IAMAccessDenied().with { $0.missingPermissions = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.CheckOnboardingStatusResponse.Finding.IAMAccessDenied"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    public enum OneOf_FindingType: Codable, Equatable, Sendable {
      /// PAM's service account is being denied access by Cloud IAM.
      indirect case iamAccessDenied(CheckOnboardingStatusResponse.Finding.IAMAccessDenied?)
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.CheckOnboardingStatusResponse.Finding"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.CheckOnboardingStatusResponse"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
