// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Response message for `CheckOnboardingStatus` method.
public struct CheckOnboardingStatusResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The service account that PAM uses to act on this resource.
  public var serviceAccount: Swift.String = Swift.String()

  /// List of issues that are preventing PAM from functioning for this resource
  /// and need to be fixed to complete onboarding. Some issues might not be
  /// detected or reported.
  public var findings: [CheckOnboardingStatusResponse.Finding] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `CheckOnboardingStatusResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CheckOnboardingStatusResponse().with { $0.serviceAccount = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let serviceAccount = CodingKeys(stringValue: "serviceAccount")
    static let findings = CodingKeys(stringValue: "findings")

    static let _knownKeys: Set<Swift.String> = [
      "serviceAccount",
      "findings",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAccount) {
      self.serviceAccount = value
    }
    if let value = try container.decodeIfPresent(
      [CheckOnboardingStatusResponse.Finding].self, forKey: .findings)
    {
      self.findings = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)
    try container.encode(self.findings, forKey: .findings)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Finding represents an issue which prevents PAM from functioning properly
  /// for this resource.
  public struct Finding: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    public var findingType: OneOf_FindingType? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `Finding`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Finding().with { $0.iamAccessDenied = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let iamAccessDenied = CodingKeys(stringValue: "iamAccessDenied")

      static let _knownKeys: Set<Swift.String> = [
        "iamAccessDenied"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var findingType: OneOf_FindingType? = nil
      let findingTypeCheckAndSet = {
        if findingType != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'findingType'"))
        }
        findingType = $0
      }
      if let iamAccessDenied = try container.decodeIfPresent(
        CheckOnboardingStatusResponse.Finding.IAMAccessDenied?.self, forKey: .iamAccessDenied)
      {
        try findingTypeCheckAndSet(.iamAccessDenied(iamAccessDenied))
      }
      self.findingType = findingType
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.findingType {
        switch choice {
        case .iamAccessDenied(let value):
          try container.encode(value, forKey: .iamAccessDenied)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// PAM's service account is being denied access by Cloud IAM.
    /// This can be fixed by granting a role that contains the missing
    /// permissions to the service account or exempting it from deny policies if
    /// they are blocking the access.
    public struct IAMAccessDenied: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// List of permissions that are being denied.
      public var missingPermissions: [Swift.String] = []

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

      /// Initialize a new instance of `IAMAccessDenied`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = IAMAccessDenied().with { $0.missingPermissions = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let missingPermissions = CodingKeys(stringValue: "missingPermissions")

        static let _knownKeys: Set<Swift.String> = [
          "missingPermissions"
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(
          [Swift.String].self, forKey: .missingPermissions)
        {
          self.missingPermissions = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleCloudWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.missingPermissions, forKey: .missingPermissions)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.CheckOnboardingStatusResponse.Finding.IAMAccessDenied"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    public enum OneOf_FindingType: Codable, Equatable, Sendable {
      /// PAM's service account is being denied access by Cloud IAM.
      indirect case iamAccessDenied(CheckOnboardingStatusResponse.Finding.IAMAccessDenied?)
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.CheckOnboardingStatusResponse.Finding"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.CheckOnboardingStatusResponse"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
