// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Message for creating an entitlement.
public struct CreateEntitlementRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Name of the parent resource for the entitlement.
  /// Possible formats:
  ///
  /// * `organizations/{organization-number}/locations/{region}`
  /// * `folders/{folder-number}/locations/{region}`
  /// * `projects/{project-id|project-number}/locations/{region}`
  public var parent: Swift.String = Swift.String()

  /// Required. The ID to use for this entitlement. This becomes the last part of
  /// the resource name.
  ///
  /// This value should be 4-63 characters in length, and valid characters are
  /// "[a-z]", "[0-9]", and "-". The first character should be from [a-z].
  ///
  /// This value should be unique among all other entitlements under the
  /// specified `parent`.
  public var entitlementId: Swift.String = Swift.String()

  /// Required. The resource being created
  public var entitlement: Entitlement? = nil

  /// Optional. An optional request ID to identify requests. Specify a unique
  /// request ID so that if you must retry your request, the server knows to
  /// ignore the request if it has already been completed. The server guarantees
  /// this for at least 60 minutes after the first request.
  ///
  /// For example, consider a situation where you make an initial request and the
  /// request times out. If you make the request again with the same request
  /// ID, the server can check if original operation with the same request ID
  /// was received, and if so, ignores the second request and returns the
  /// previous operation's response. This prevents clients from accidentally
  /// creating duplicate entitlements.
  ///
  /// The request ID must be a valid UUID with the exception that zero UUID is
  /// not supported (00000000-0000-0000-0000-000000000000).
  public var requestId: Swift.String = Swift.String()

  /// Initialize a new instance of `CreateEntitlementRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateEntitlementRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.CreateEntitlementRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
