// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// An entitlement defines the eligibility of a set of users to obtain
/// predefined access for some time possibly after going through an approval
/// workflow.
public struct Entitlement: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. Name of the entitlement.
  /// Possible formats:
  ///
  /// * `organizations/{organization-number}/locations/{region}/entitlements/{entitlement-id}`
  /// * `folders/{folder-number}/locations/{region}/entitlements/{entitlement-id}`
  /// * `projects/{project-id|project-number}/locations/{region}/entitlements/{entitlement-id}`
  public var name: Swift.String = Swift.String()

  /// Output only. Create time stamp.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Update time stamp.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. Who can create grants using this entitlement. This list should
  /// contain at most one entry.
  public var eligibleUsers: [AccessControlEntry] = []

  /// Optional. The approvals needed before access are granted to a requester. No
  /// approvals are needed if this field is null.
  public var approvalWorkflow: ApprovalWorkflow? = nil

  /// The access granted to a requester on successful approval.
  public var privilegedAccess: PrivilegedAccess? = nil

  /// Required. The maximum amount of time that access is granted for a request.
  /// A requester can ask for a duration less than this, but never more.
  public var maxRequestDuration: GoogleCloudWkt.Duration? = nil

  /// Output only. Current state of this entitlement.
  public var state: Entitlement.State = Entitlement.State()

  /// Required. The manner in which the requester should provide a justification
  /// for requesting access.
  public var requesterJustificationConfig: Entitlement.RequesterJustificationConfig? = nil

  /// Optional. Additional email addresses to be notified based on actions taken.
  public var additionalNotificationTargets: Entitlement.AdditionalNotificationTargets? = nil

  /// An `etag` is used for optimistic concurrency control as a way to prevent
  /// simultaneous updates to the same entitlement. An `etag` is returned in the
  /// response to `GetEntitlement` and the caller should put the `etag` in the
  /// request to `UpdateEntitlement` so that their change is applied on
  /// the same version. If this field is omitted or if there is a mismatch while
  /// updating an entitlement, then the server rejects the request.
  public var etag: Swift.String = Swift.String()

  /// Initialize a new instance of `Entitlement`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Entitlement().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Defines how a requester must provide a justification when requesting
  /// access.
  public struct RequesterJustificationConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// This is a required field and the user must explicitly opt out if a
    /// justification from the requester isn't mandatory.
    public var justificationType: OneOf_JustificationType? = nil

    /// Initialize a new instance of `RequesterJustificationConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RequesterJustificationConfig().with { $0.notMandatory = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case notMandatory = "notMandatory"
      case unstructured = "unstructured"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var justificationType: OneOf_JustificationType? = nil
      let justificationTypeCheckAndSet = {
        if justificationType != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'justificationType'"))
        }
        justificationType = $0
      }
      if let notMandatory = try container.decodeIfPresent(
        Entitlement.RequesterJustificationConfig.NotMandatory?.self, forKey: .notMandatory)
      {
        try justificationTypeCheckAndSet(.notMandatory(notMandatory))
      }
      if let unstructured = try container.decodeIfPresent(
        Entitlement.RequesterJustificationConfig.Unstructured?.self, forKey: .unstructured)
      {
        try justificationTypeCheckAndSet(.unstructured(unstructured))
      }
      self.justificationType = justificationType
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.justificationType {
        switch choice {
        case .notMandatory(let value):
          try container.encode(value, forKey: .notMandatory)
        case .unstructured(let value):
          try container.encode(value, forKey: .unstructured)
        }
      }
    }

    /// The justification is not mandatory but can be provided in any of the
    /// supported formats.
    public struct NotMandatory: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Initialize a new instance of `NotMandatory`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = NotMandatory().with { $0.<placeholder> = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.Entitlement.RequesterJustificationConfig.NotMandatory"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// The requester has to provide a justification in the form of a string.
    public struct Unstructured: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Initialize a new instance of `Unstructured`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Unstructured().with { $0.<placeholder> = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.Entitlement.RequesterJustificationConfig.Unstructured"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// This is a required field and the user must explicitly opt out if a
    /// justification from the requester isn't mandatory.
    public enum OneOf_JustificationType: Codable, Equatable, Sendable {
      /// This option means the requester isn't required to provide a
      /// justification.
      indirect case notMandatory(Entitlement.RequesterJustificationConfig.NotMandatory?)
      /// This option means the requester must provide a string as
      /// justification. If this is selected, the server allows the requester
      /// to provide a justification but doesn't validate it.
      indirect case unstructured(Entitlement.RequesterJustificationConfig.Unstructured?)
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.Entitlement.RequesterJustificationConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// `AdditionalNotificationTargets` includes email addresses to be notified.
  public struct AdditionalNotificationTargets: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. Additional email addresses to be notified when a principal
    /// (requester) is granted access.
    public var adminEmailRecipients: [Swift.String] = []

    /// Optional. Additional email address to be notified about an eligible
    /// entitlement.
    public var requesterEmailRecipients: [Swift.String] = []

    /// Initialize a new instance of `AdditionalNotificationTargets`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AdditionalNotificationTargets().with { $0.adminEmailRecipients = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.Entitlement.AdditionalNotificationTargets"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Different states an entitlement can be in.
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified state. This value is never returned by the server.
    case unspecified
    /// The entitlement is being created.
    case creating
    /// The entitlement is available for requesting access.
    case available
    /// The entitlement is being deleted.
    case deleting
    /// The entitlement has been deleted.
    case deleted
    /// The entitlement is being updated.
    case updating
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .available: return 2
      case .deleting: return 3
      case .deleted: return 4
      case .updating: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .available: return "AVAILABLE"
      case .deleting: return "DELETING"
      case .deleted: return "DELETED"
      case .updating: return "UPDATING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "AVAILABLE": self = .available
      case "DELETING": self = .deleting
      case "DELETED": self = .deleted
      case "UPDATING": self = .updating
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .available
      case 3: self = .deleting
      case 4: self = .deleted
      case 5: self = .updating
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .available: return try container.encode(2)
      case .deleting: return try container.encode(3)
      case .deleted: return try container.encode(4)
      case .updating: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.Entitlement"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
