// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt
import GoogleRpc

/// A grant represents a request from a user for obtaining the access specified
/// in an entitlement they are eligible for.
public struct Grant: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. Name of this grant.
  /// Possible formats:
  ///
  /// * `organizations/{organization-number}/locations/{region}/entitlements/{entitlement-id}/grants/{grant-id}`
  /// * `folders/{folder-number}/locations/{region}/entitlements/{entitlement-id}/grants/{grant-id}`
  /// * `projects/{project-id|project-number}/locations/{region}/entitlements/{entitlement-id}/grants/{grant-id}`
  ///
  /// The last segment of this name (`{grant-id}`) is autogenerated.
  public var name: Swift.String = Swift.String()

  /// Output only. Create time stamp.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Update time stamp.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Username of the user who created this grant.
  public var requester: Swift.String = Swift.String()

  /// Required. The amount of time access is needed for. This value should be
  /// less than the `max_request_duration` value of the entitlement.
  public var requestedDuration: GoogleCloudWkt.Duration? = nil

  /// Optional. Justification of why this access is needed.
  public var justification: Justification? = nil

  /// Output only. Current state of this grant.
  public var state: Grant.State = Grant.State()

  /// Output only. Timeline of this grant.
  public var timeline: Grant.Timeline? = nil

  /// Output only. The access that would be granted by this grant.
  public var privilegedAccess: PrivilegedAccess? = nil

  /// Output only. Audit trail of access provided by this grant. If unspecified
  /// then access was never granted.
  public var auditTrail: Grant.AuditTrail? = nil

  /// Optional. Additional email addresses to notify for all the actions
  /// performed on the grant.
  public var additionalEmailRecipients: [Swift.String] = []

  /// Output only. Flag set by the PAM system to indicate that policy bindings
  /// made by this grant have been modified from outside PAM.
  ///
  /// After it is set, this flag remains set forever irrespective of the grant
  /// state. A `true` value here indicates that PAM no longer has any certainty
  /// on the access a user has because of this grant.
  public var externallyModified: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `Grant`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Grant().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Timeline of a grant describing what happened to it and when.
  public struct Timeline: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. The events that have occurred on this grant. This list
    /// contains entries in the same order as they occurred. The first entry is
    /// always be of type `Requested` and there is always at least one entry in
    /// this array.
    public var events: [Grant.Timeline.Event] = []

    /// Initialize a new instance of `Timeline`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Timeline().with { $0.events = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// A single operation on the grant.
    public struct Event: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Output only. The time (as recorded at server) when this event occurred.
      public var eventTime: GoogleCloudWkt.Timestamp? = nil

      public var event: OneOf_Event? = nil

      /// Initialize a new instance of `Event`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Event().with { $0.requested = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private enum CodingKeys: Swift.String, CodingKey {
        case requested = "requested"
        case approved = "approved"
        case denied = "denied"
        case revoked = "revoked"
        case scheduled = "scheduled"
        case activated = "activated"
        case activationFailed = "activationFailed"
        case expired = "expired"
        case ended = "ended"
        case externallyModified = "externallyModified"
        case withdrawn = "withdrawn"
        case eventTime = "eventTime"
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.eventTime = try container.decodeIfPresent(
          GoogleCloudWkt.Timestamp.self, forKey: .eventTime)

        var event: OneOf_Event? = nil
        let eventCheckAndSet = {
          if event != nil {
            throw DecodingError.dataCorrupted(
              DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Multiple values set for oneof 'event'"))
          }
          event = $0
        }
        if let requested = try container.decodeIfPresent(
          Grant.Timeline.Event.Requested?.self, forKey: .requested)
        {
          try eventCheckAndSet(.requested(requested))
        }
        if let approved = try container.decodeIfPresent(
          Grant.Timeline.Event.Approved?.self, forKey: .approved)
        {
          try eventCheckAndSet(.approved(approved))
        }
        if let denied = try container.decodeIfPresent(
          Grant.Timeline.Event.Denied?.self, forKey: .denied)
        {
          try eventCheckAndSet(.denied(denied))
        }
        if let revoked = try container.decodeIfPresent(
          Grant.Timeline.Event.Revoked?.self, forKey: .revoked)
        {
          try eventCheckAndSet(.revoked(revoked))
        }
        if let scheduled = try container.decodeIfPresent(
          Grant.Timeline.Event.Scheduled?.self, forKey: .scheduled)
        {
          try eventCheckAndSet(.scheduled(scheduled))
        }
        if let activated = try container.decodeIfPresent(
          Grant.Timeline.Event.Activated?.self, forKey: .activated)
        {
          try eventCheckAndSet(.activated(activated))
        }
        if let activationFailed = try container.decodeIfPresent(
          Grant.Timeline.Event.ActivationFailed?.self, forKey: .activationFailed)
        {
          try eventCheckAndSet(.activationFailed(activationFailed))
        }
        if let expired = try container.decodeIfPresent(
          Grant.Timeline.Event.Expired?.self, forKey: .expired)
        {
          try eventCheckAndSet(.expired(expired))
        }
        if let ended = try container.decodeIfPresent(
          Grant.Timeline.Event.Ended?.self, forKey: .ended)
        {
          try eventCheckAndSet(.ended(ended))
        }
        if let externallyModified = try container.decodeIfPresent(
          Grant.Timeline.Event.ExternallyModified?.self, forKey: .externallyModified)
        {
          try eventCheckAndSet(.externallyModified(externallyModified))
        }
        if let withdrawn = try container.decodeIfPresent(
          Grant.Timeline.Event.Withdrawn?.self, forKey: .withdrawn)
        {
          try eventCheckAndSet(.withdrawn(withdrawn))
        }
        self.event = event
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.eventTime, forKey: .eventTime)

        if let choice = self.event {
          switch choice {
          case .requested(let value):
            try container.encode(value, forKey: .requested)
          case .approved(let value):
            try container.encode(value, forKey: .approved)
          case .denied(let value):
            try container.encode(value, forKey: .denied)
          case .revoked(let value):
            try container.encode(value, forKey: .revoked)
          case .scheduled(let value):
            try container.encode(value, forKey: .scheduled)
          case .activated(let value):
            try container.encode(value, forKey: .activated)
          case .activationFailed(let value):
            try container.encode(value, forKey: .activationFailed)
          case .expired(let value):
            try container.encode(value, forKey: .expired)
          case .ended(let value):
            try container.encode(value, forKey: .ended)
          case .externallyModified(let value):
            try container.encode(value, forKey: .externallyModified)
          case .withdrawn(let value):
            try container.encode(value, forKey: .withdrawn)
          }
        }
      }

      /// An event representing that a grant was requested.
      public struct Requested: Codable, Equatable, GoogleCloudWkt._AnyPackable,
        Sendable
      {
        /// Output only. The time at which this grant expires unless the approval
        /// workflow completes. If omitted, then the request never expires.
        public var expireTime: GoogleCloudWkt.Timestamp? = nil

        /// Initialize a new instance of `Requested`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = Requested().with { $0.expireTime = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.Grant.Timeline.Event.Requested"
        }
        public init(fromAny any: GoogleCloudWkt.`Any`) throws {
          self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWkt.Struct {
          return try GoogleCloudWkt._slowAnySerialize(message: self)
        }
      }

      /// An event representing that the grant was approved.
      public struct Approved: Codable, Equatable, GoogleCloudWkt._AnyPackable,
        Sendable
      {
        /// Output only. The reason provided by the approver for approving the
        /// grant.
        public var reason: Swift.String = Swift.String()

        /// Output only. Username of the user who approved the grant.
        public var actor: Swift.String = Swift.String()

        /// Initialize a new instance of `Approved`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = Approved().with { $0.reason = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.Grant.Timeline.Event.Approved"
        }
        public init(fromAny any: GoogleCloudWkt.`Any`) throws {
          self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWkt.Struct {
          return try GoogleCloudWkt._slowAnySerialize(message: self)
        }
      }

      /// An event representing that the grant was denied.
      public struct Denied: Codable, Equatable, GoogleCloudWkt._AnyPackable,
        Sendable
      {
        /// Output only. The reason provided by the approver for denying the
        /// grant.
        public var reason: Swift.String = Swift.String()

        /// Output only. Username of the user who denied the grant.
        public var actor: Swift.String = Swift.String()

        /// Initialize a new instance of `Denied`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = Denied().with { $0.reason = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.Grant.Timeline.Event.Denied"
        }
        public init(fromAny any: GoogleCloudWkt.`Any`) throws {
          self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWkt.Struct {
          return try GoogleCloudWkt._slowAnySerialize(message: self)
        }
      }

      /// An event representing that the grant was revoked.
      public struct Revoked: Codable, Equatable, GoogleCloudWkt._AnyPackable,
        Sendable
      {
        /// Output only. The reason provided by the user for revoking the grant.
        public var reason: Swift.String = Swift.String()

        /// Output only. Username of the user who revoked the grant.
        public var actor: Swift.String = Swift.String()

        /// Initialize a new instance of `Revoked`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = Revoked().with { $0.reason = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.Grant.Timeline.Event.Revoked"
        }
        public init(fromAny any: GoogleCloudWkt.`Any`) throws {
          self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWkt.Struct {
          return try GoogleCloudWkt._slowAnySerialize(message: self)
        }
      }

      /// An event representing that the grant was withdrawn.
      public struct Withdrawn: Codable, Equatable, GoogleCloudWkt._AnyPackable,
        Sendable
      {
        /// Initialize a new instance of `Withdrawn`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = Withdrawn().with { $0.<placeholder> = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.Grant.Timeline.Event.Withdrawn"
        }
        public init(fromAny any: GoogleCloudWkt.`Any`) throws {
          self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWkt.Struct {
          return try GoogleCloudWkt._slowAnySerialize(message: self)
        }
      }

      /// An event representing that the grant has been scheduled to be
      /// activated later.
      public struct Scheduled: Codable, Equatable, GoogleCloudWkt._AnyPackable,
        Sendable
      {
        /// Output only. The time at which the access is granted.
        public var scheduledActivationTime: GoogleCloudWkt.Timestamp? = nil

        /// Initialize a new instance of `Scheduled`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = Scheduled().with { $0.scheduledActivationTime = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.Grant.Timeline.Event.Scheduled"
        }
        public init(fromAny any: GoogleCloudWkt.`Any`) throws {
          self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWkt.Struct {
          return try GoogleCloudWkt._slowAnySerialize(message: self)
        }
      }

      /// An event representing that the grant was successfully
      /// activated.
      public struct Activated: Codable, Equatable, GoogleCloudWkt._AnyPackable,
        Sendable
      {
        /// Initialize a new instance of `Activated`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = Activated().with { $0.<placeholder> = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.Grant.Timeline.Event.Activated"
        }
        public init(fromAny any: GoogleCloudWkt.`Any`) throws {
          self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWkt.Struct {
          return try GoogleCloudWkt._slowAnySerialize(message: self)
        }
      }

      /// An event representing that the grant activation failed.
      public struct ActivationFailed: Codable, Equatable, GoogleCloudWkt._AnyPackable,
        Sendable
      {
        /// Output only. The error that occurred while activating the grant.
        public var error: GoogleRpc.Status? = nil

        /// Initialize a new instance of `ActivationFailed`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = ActivationFailed().with { $0.error = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.Grant.Timeline.Event.ActivationFailed"
        }
        public init(fromAny any: GoogleCloudWkt.`Any`) throws {
          self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWkt.Struct {
          return try GoogleCloudWkt._slowAnySerialize(message: self)
        }
      }

      /// An event representing that the grant was expired.
      public struct Expired: Codable, Equatable, GoogleCloudWkt._AnyPackable,
        Sendable
      {
        /// Initialize a new instance of `Expired`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = Expired().with { $0.<placeholder> = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.Grant.Timeline.Event.Expired"
        }
        public init(fromAny any: GoogleCloudWkt.`Any`) throws {
          self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWkt.Struct {
          return try GoogleCloudWkt._slowAnySerialize(message: self)
        }
      }

      /// An event representing that the grant has ended.
      public struct Ended: Codable, Equatable, GoogleCloudWkt._AnyPackable,
        Sendable
      {
        /// Initialize a new instance of `Ended`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = Ended().with { $0.<placeholder> = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.Grant.Timeline.Event.Ended"
        }
        public init(fromAny any: GoogleCloudWkt.`Any`) throws {
          self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWkt.Struct {
          return try GoogleCloudWkt._slowAnySerialize(message: self)
        }
      }

      /// An event representing that the policy bindings made by this grant were
      /// modified externally.
      public struct ExternallyModified: Codable, Equatable, GoogleCloudWkt._AnyPackable,
        Sendable
      {
        /// Initialize a new instance of `ExternallyModified`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = ExternallyModified().with { $0.<placeholder> = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.Grant.Timeline.Event.ExternallyModified"
        }
        public init(fromAny any: GoogleCloudWkt.`Any`) throws {
          self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWkt.Struct {
          return try GoogleCloudWkt._slowAnySerialize(message: self)
        }
      }

      public enum OneOf_Event: Codable, Equatable, Sendable {
        /// The grant was requested.
        indirect case requested(Grant.Timeline.Event.Requested?)
        /// The grant was approved.
        indirect case approved(Grant.Timeline.Event.Approved?)
        /// The grant was denied.
        indirect case denied(Grant.Timeline.Event.Denied?)
        /// The grant was revoked.
        indirect case revoked(Grant.Timeline.Event.Revoked?)
        /// The grant has been scheduled to give access.
        indirect case scheduled(Grant.Timeline.Event.Scheduled?)
        /// The grant was successfully activated to give access.
        indirect case activated(Grant.Timeline.Event.Activated?)
        /// There was a non-retriable error while trying to give access.
        indirect case activationFailed(Grant.Timeline.Event.ActivationFailed?)
        /// The approval workflow did not complete in the necessary duration,
        /// and so the grant is expired.
        indirect case expired(Grant.Timeline.Event.Expired?)
        /// Access given by the grant ended automatically as the approved
        /// duration was over.
        indirect case ended(Grant.Timeline.Event.Ended?)
        /// The policy bindings made by grant have been modified outside of PAM.
        indirect case externallyModified(Grant.Timeline.Event.ExternallyModified?)
        /// The grant was withdrawn.
        indirect case withdrawn(Grant.Timeline.Event.Withdrawn?)
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.Grant.Timeline.Event"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.Grant.Timeline"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Audit trail for the access provided by this grant.
  public struct AuditTrail: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. The time at which access was given.
    public var accessGrantTime: GoogleCloudWkt.Timestamp? = nil

    /// Output only. The time at which the system removed access. This could be
    /// because of an automatic expiry or because of a revocation.
    ///
    /// If unspecified, then access hasn't been removed yet.
    public var accessRemoveTime: GoogleCloudWkt.Timestamp? = nil

    /// Initialize a new instance of `AuditTrail`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AuditTrail().with { $0.accessGrantTime = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.Grant.AuditTrail"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Different states a grant can be in.
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified state. This value is never returned by the server.
    case unspecified
    /// The entitlement had an approval workflow configured and this grant is
    /// waiting for the workflow to complete.
    case approvalAwaited
    /// The approval workflow completed with a denied result. No access is
    /// granted for this grant. This is a terminal state.
    case denied
    /// The approval workflow completed successfully with an approved result or
    /// none was configured. Access is provided at an appropriate time.
    case scheduled
    /// Access is being given.
    case activating
    /// Access was successfully given and is currently active.
    case active
    /// The system could not give access due to a non-retriable error. This is a
    /// terminal state.
    case activationFailed
    /// Expired after waiting for the approval workflow to complete. This is a
    /// terminal state.
    case expired
    /// Access is being revoked.
    case revoking
    /// Access was revoked by a user. This is a terminal state.
    case revoked
    /// System took back access as the requested duration was over. This is a
    /// terminal state.
    case ended
    /// Access is being withdrawn.
    case withdrawing
    /// Grant was withdrawn by the grant owner. This is a terminal state.
    case withdrawn
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .approvalAwaited: return 1
      case .denied: return 3
      case .scheduled: return 4
      case .activating: return 5
      case .active: return 6
      case .activationFailed: return 7
      case .expired: return 8
      case .revoking: return 9
      case .revoked: return 10
      case .ended: return 11
      case .withdrawing: return 12
      case .withdrawn: return 13
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .approvalAwaited: return "APPROVAL_AWAITED"
      case .denied: return "DENIED"
      case .scheduled: return "SCHEDULED"
      case .activating: return "ACTIVATING"
      case .active: return "ACTIVE"
      case .activationFailed: return "ACTIVATION_FAILED"
      case .expired: return "EXPIRED"
      case .revoking: return "REVOKING"
      case .revoked: return "REVOKED"
      case .ended: return "ENDED"
      case .withdrawing: return "WITHDRAWING"
      case .withdrawn: return "WITHDRAWN"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "APPROVAL_AWAITED": self = .approvalAwaited
      case "DENIED": self = .denied
      case "SCHEDULED": self = .scheduled
      case "ACTIVATING": self = .activating
      case "ACTIVE": self = .active
      case "ACTIVATION_FAILED": self = .activationFailed
      case "EXPIRED": self = .expired
      case "REVOKING": self = .revoking
      case "REVOKED": self = .revoked
      case "ENDED": self = .ended
      case "WITHDRAWING": self = .withdrawing
      case "WITHDRAWN": self = .withdrawn
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .approvalAwaited
      case 3: self = .denied
      case 4: self = .scheduled
      case 5: self = .activating
      case 6: self = .active
      case 7: self = .activationFailed
      case 8: self = .expired
      case 9: self = .revoking
      case 10: self = .revoked
      case 11: self = .ended
      case 12: self = .withdrawing
      case 13: self = .withdrawn
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .approvalAwaited: return try container.encode(1)
      case .denied: return try container.encode(3)
      case .scheduled: return try container.encode(4)
      case .activating: return try container.encode(5)
      case .active: return try container.encode(6)
      case .activationFailed: return try container.encode(7)
      case .expired: return try container.encode(8)
      case .revoking: return try container.encode(9)
      case .revoked: return try container.encode(10)
      case .ended: return try container.encode(11)
      case .withdrawing: return try container.encode(12)
      case .withdrawn: return try container.encode(13)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.Grant"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
