// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Justification represents a justification for requesting access.
public struct Justification: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  public var justification: OneOf_Justification? = nil

  /// Initialize a new instance of `Justification`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Justification().with { $0.unstructuredJustification = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case unstructuredJustification = "unstructuredJustification"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var justification: OneOf_Justification? = nil
    let justificationCheckAndSet = {
      if justification != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'justification'"))
      }
      justification = $0
    }
    if let unstructuredJustification = try container.decodeIfPresent(
      Swift.String.self, forKey: .unstructuredJustification)
    {
      try justificationCheckAndSet(.unstructuredJustification(unstructuredJustification))
    }
    self.justification = justification
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.justification {
      switch choice {
      case .unstructuredJustification(let value):
        try container.encode(value, forKey: .unstructuredJustification)
      }
    }
  }

  public enum OneOf_Justification: Codable, Equatable, Sendable {
    /// A free form textual justification. The system only ensures that this
    /// is not empty. No other kind of validation is performed on the string.
    case unstructuredJustification(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.Justification"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
