// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// A manual approval workflow where users who are designated as approvers
/// need to call the `ApproveGrant`/`DenyGrant` APIs for a grant. The workflow
/// can consist of multiple serial steps where each step defines who can act as
/// approver in that step and how many of those users should approve before the
/// workflow moves to the next step.
///
/// This can be used to create approval workflows such as:
///
/// * Require an approval from any user in a group G.
/// * Require an approval from any k number of users from a Group G.
/// * Require an approval from any user in a group G and then from a user U.
///
/// A single user might be part of the `approvers` ACL for multiple steps in this
/// workflow, but they can only approve once and that approval is only considered
/// to satisfy the approval step at which it was granted.
public struct ManualApprovals: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Do the approvers need to provide a justification for their
  /// actions?
  public var requireApproverJustification: Swift.Bool = Swift.Bool()

  /// Optional. List of approval steps in this workflow. These steps are followed
  /// in the specified order sequentially. Only 1 step is supported.
  public var steps: [ManualApprovals.Step] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ManualApprovals`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ManualApprovals().with { $0.requireApproverJustification = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let requireApproverJustification = CodingKeys(
      stringValue: "requireApproverJustification")
    static let steps = CodingKeys(stringValue: "steps")

    static let _knownKeys: Set<Swift.String> = [
      "requireApproverJustification",
      "steps",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .requireApproverJustification)
    {
      self.requireApproverJustification = value
    }
    if let value = try container.decodeIfPresent([ManualApprovals.Step].self, forKey: .steps) {
      self.steps = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.requireApproverJustification, forKey: .requireApproverJustification)
    try container.encode(self.steps, forKey: .steps)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Step represents a logical step in a manual approval workflow.
  public struct Step: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. The potential set of approvers in this step. This list must
    /// contain at most one entry.
    public var approvers: [AccessControlEntry] = []

    /// Required. How many users from the above list need to approve. If there
    /// aren't enough distinct users in the list, then the workflow indefinitely
    /// blocks. Should always be greater than 0. 1 is the only supported value.
    public var approvalsNeeded: Swift.Int32 = Swift.Int32()

    /// Optional. Additional email addresses to be notified when a grant is
    /// pending approval.
    public var approverEmailRecipients: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Step`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Step().with { $0.approvers = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let approvers = CodingKeys(stringValue: "approvers")
      static let approvalsNeeded = CodingKeys(stringValue: "approvalsNeeded")
      static let approverEmailRecipients = CodingKeys(stringValue: "approverEmailRecipients")

      static let _knownKeys: Set<Swift.String> = [
        "approvers",
        "approvalsNeeded",
        "approverEmailRecipients",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([AccessControlEntry].self, forKey: .approvers) {
        self.approvers = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .approvalsNeeded) {
        self.approvalsNeeded = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String].self, forKey: .approverEmailRecipients)
      {
        self.approverEmailRecipients = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.approvers, forKey: .approvers)
      try container.encode(self.approvalsNeeded, forKey: .approvalsNeeded)
      try container.encode(self.approverEmailRecipients, forKey: .approverEmailRecipients)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.ManualApprovals.Step"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.ManualApprovals"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
