// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Privileged access that this service can be used to gate.
public struct PrivilegedAccess: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  public var accessType: OneOf_AccessType? = nil

  /// Initialize a new instance of `PrivilegedAccess`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PrivilegedAccess().with { $0.gcpIamAccess = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case gcpIamAccess = "gcpIamAccess"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var accessType: OneOf_AccessType? = nil
    let accessTypeCheckAndSet = {
      if accessType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'accessType'"))
      }
      accessType = $0
    }
    if let gcpIamAccess = try container.decodeIfPresent(
      PrivilegedAccess.GcpIamAccess?.self, forKey: .gcpIamAccess)
    {
      try accessTypeCheckAndSet(.gcpIamAccess(gcpIamAccess))
    }
    self.accessType = accessType
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.accessType {
      switch choice {
      case .gcpIamAccess(let value):
        try container.encode(value, forKey: .gcpIamAccess)
      }
    }
  }

  /// `GcpIamAccess` represents IAM based access control on a Google Cloud
  /// resource. Refer to https://cloud.google.com/iam/docs to understand more
  /// about IAM.
  public struct GcpIamAccess: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The type of this resource.
    public var resourceType: Swift.String = Swift.String()

    /// Required. Name of the resource.
    public var resource: Swift.String = Swift.String()

    /// Required. Role bindings that are created on successful grant.
    public var roleBindings: [PrivilegedAccess.GcpIamAccess.RoleBinding] = []

    /// Initialize a new instance of `GcpIamAccess`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GcpIamAccess().with { $0.resourceType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// IAM role bindings that are created after a successful grant.
    public struct RoleBinding: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Required. IAM role to be granted.
      /// https://cloud.google.com/iam/docs/roles-overview.
      public var role: Swift.String = Swift.String()

      /// Optional. The expression field of the IAM condition to be associated
      /// with the role. If specified, a user with an active grant for this
      /// entitlement is able to access the resource only if this condition
      /// evaluates to true for their request.
      ///
      /// This field uses the same CEL format as IAM and supports all attributes
      /// that IAM supports, except tags.
      /// https://cloud.google.com/iam/docs/conditions-overview#attributes.
      public var conditionExpression: Swift.String = Swift.String()

      /// Initialize a new instance of `RoleBinding`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = RoleBinding().with { $0.role = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.PrivilegedAccess.GcpIamAccess.RoleBinding"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.PrivilegedAccess.GcpIamAccess"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public enum OneOf_AccessType: Codable, Equatable, Sendable {
    /// Access to a Google Cloud resource through IAM.
    indirect case gcpIamAccess(PrivilegedAccess.GcpIamAccess?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.PrivilegedAccess"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
