// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  final class PrivilegedAccessManagerRetry: PrivilegedAccessManagerStub {
    let inner: any PrivilegedAccessManagerStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any PrivilegedAccessManagerStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func checkOnboardingStatus(
      request: CheckOnboardingStatusRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.CheckOnboardingStatusResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: CheckOnboardingStatusRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudPrivilegedAccessManagerV1.CheckOnboardingStatusResponse
          in
          return try await self.inner.checkOnboardingStatus(request: r, options: o)
        })
    }

    public func listEntitlements(
      request: ListEntitlementsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.ListEntitlementsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListEntitlementsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudPrivilegedAccessManagerV1.ListEntitlementsResponse
          in
          return try await self.inner.listEntitlements(request: r, options: o)
        })
    }

    public func searchEntitlements(
      request: SearchEntitlementsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.SearchEntitlementsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: SearchEntitlementsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudPrivilegedAccessManagerV1.SearchEntitlementsResponse
          in
          return try await self.inner.searchEntitlements(request: r, options: o)
        })
    }

    public func getEntitlement(
      request: GetEntitlementRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Entitlement {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetEntitlementRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudPrivilegedAccessManagerV1.Entitlement
          in
          return try await self.inner.getEntitlement(request: r, options: o)
        })
    }

    public func createEntitlement(
      request: CreateEntitlementRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateEntitlementRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createEntitlement(request: r, options: o)
        })
    }

    public func deleteEntitlement(
      request: DeleteEntitlementRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteEntitlementRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteEntitlement(request: r, options: o)
        })
    }

    public func updateEntitlement(
      request: UpdateEntitlementRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateEntitlementRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateEntitlement(request: r, options: o)
        })
    }

    public func listGrants(
      request: ListGrantsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.ListGrantsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListGrantsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudPrivilegedAccessManagerV1.ListGrantsResponse
          in
          return try await self.inner.listGrants(request: r, options: o)
        })
    }

    public func searchGrants(
      request: SearchGrantsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.SearchGrantsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: SearchGrantsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudPrivilegedAccessManagerV1.SearchGrantsResponse
          in
          return try await self.inner.searchGrants(request: r, options: o)
        })
    }

    public func getGrant(
      request: GetGrantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Grant {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetGrantRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudPrivilegedAccessManagerV1.Grant
          in
          return try await self.inner.getGrant(request: r, options: o)
        })
    }

    public func createGrant(
      request: CreateGrantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Grant {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateGrantRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudPrivilegedAccessManagerV1.Grant
          in
          return try await self.inner.createGrant(request: r, options: o)
        })
    }

    public func approveGrant(
      request: ApproveGrantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Grant {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ApproveGrantRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudPrivilegedAccessManagerV1.Grant
          in
          return try await self.inner.approveGrant(request: r, options: o)
        })
    }

    public func denyGrant(
      request: DenyGrantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Grant {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DenyGrantRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudPrivilegedAccessManagerV1.Grant
          in
          return try await self.inner.denyGrant(request: r, options: o)
        })
    }

    public func revokeGrant(
      request: RevokeGrantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: RevokeGrantRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.revokeGrant(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }
  }
}
