// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class PrivilegedAccessManagerLogging: PrivilegedAccessManagerStub {
    let inner: any PrivilegedAccessManagerStub
    let logger: Logger

    public init(_ inner: any PrivilegedAccessManagerStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-privilegedaccessmanager-v1"
      logger[metadataKey: "gcp.client.service"] = "privilegedaccessmanager"
      logger[metadataKey: "gcp.experimental.swift.client"] = "PrivilegedAccessManager"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func checkOnboardingStatus(
      request: CheckOnboardingStatusRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.CheckOnboardingStatusResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "checkOnboardingStatus",
        action: {
          (r: CheckOnboardingStatusRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudPrivilegedAccessManagerV1.CheckOnboardingStatusResponse
          in
          return try await self.inner.checkOnboardingStatus(request: r, options: o)
        })
    }

    public func listEntitlements(
      request: ListEntitlementsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.ListEntitlementsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listEntitlements",
        action: {
          (r: ListEntitlementsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudPrivilegedAccessManagerV1.ListEntitlementsResponse
          in
          return try await self.inner.listEntitlements(request: r, options: o)
        })
    }

    public func searchEntitlements(
      request: SearchEntitlementsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.SearchEntitlementsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "searchEntitlements",
        action: {
          (r: SearchEntitlementsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudPrivilegedAccessManagerV1.SearchEntitlementsResponse
          in
          return try await self.inner.searchEntitlements(request: r, options: o)
        })
    }

    public func getEntitlement(
      request: GetEntitlementRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Entitlement {
      try await self._intercept(
        request: request,
        options: options,
        name: "getEntitlement",
        action: {
          (r: GetEntitlementRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudPrivilegedAccessManagerV1.Entitlement
          in
          return try await self.inner.getEntitlement(request: r, options: o)
        })
    }

    public func createEntitlement(
      request: CreateEntitlementRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createEntitlement",
        action: {
          (r: CreateEntitlementRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createEntitlement(request: r, options: o)
        })
    }

    public func deleteEntitlement(
      request: DeleteEntitlementRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteEntitlement",
        action: {
          (r: DeleteEntitlementRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteEntitlement(request: r, options: o)
        })
    }

    public func updateEntitlement(
      request: UpdateEntitlementRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateEntitlement",
        action: {
          (r: UpdateEntitlementRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateEntitlement(request: r, options: o)
        })
    }

    public func listGrants(
      request: ListGrantsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.ListGrantsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listGrants",
        action: {
          (r: ListGrantsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudPrivilegedAccessManagerV1.ListGrantsResponse
          in
          return try await self.inner.listGrants(request: r, options: o)
        })
    }

    public func searchGrants(
      request: SearchGrantsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.SearchGrantsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "searchGrants",
        action: {
          (r: SearchGrantsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudPrivilegedAccessManagerV1.SearchGrantsResponse
          in
          return try await self.inner.searchGrants(request: r, options: o)
        })
    }

    public func getGrant(
      request: GetGrantRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Grant {
      try await self._intercept(
        request: request,
        options: options,
        name: "getGrant",
        action: {
          (r: GetGrantRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudPrivilegedAccessManagerV1.Grant
          in
          return try await self.inner.getGrant(request: r, options: o)
        })
    }

    public func createGrant(
      request: CreateGrantRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Grant {
      try await self._intercept(
        request: request,
        options: options,
        name: "createGrant",
        action: {
          (r: CreateGrantRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudPrivilegedAccessManagerV1.Grant
          in
          return try await self.inner.createGrant(request: r, options: o)
        })
    }

    public func approveGrant(
      request: ApproveGrantRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Grant {
      try await self._intercept(
        request: request,
        options: options,
        name: "approveGrant",
        action: {
          (r: ApproveGrantRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudPrivilegedAccessManagerV1.Grant
          in
          return try await self.inner.approveGrant(request: r, options: o)
        })
    }

    public func denyGrant(
      request: DenyGrantRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Grant {
      try await self._intercept(
        request: request,
        options: options,
        name: "denyGrant",
        action: {
          (r: DenyGrantRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudPrivilegedAccessManagerV1.Grant
          in
          return try await self.inner.denyGrant(request: r, options: o)
        })
    }

    public func revokeGrant(
      request: RevokeGrantRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "revokeGrant",
        action: {
          (r: RevokeGrantRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.revokeGrant(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }
  }
}
