// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol PrivilegedAccessManagerStub {
    func checkOnboardingStatus(
      request: CheckOnboardingStatusRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.CheckOnboardingStatusResponse

    func listEntitlements(
      request: ListEntitlementsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.ListEntitlementsResponse

    func searchEntitlements(
      request: SearchEntitlementsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.SearchEntitlementsResponse

    func getEntitlement(
      request: GetEntitlementRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Entitlement

    func createEntitlement(
      request: CreateEntitlementRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteEntitlement(
      request: DeleteEntitlementRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateEntitlement(
      request: UpdateEntitlementRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listGrants(
      request: ListGrantsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.ListGrantsResponse

    func searchGrants(
      request: SearchGrantsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.SearchGrantsResponse

    func getGrant(
      request: GetGrantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Grant

    func createGrant(
      request: CreateGrantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Grant

    func approveGrant(
      request: ApproveGrantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Grant

    func denyGrant(
      request: DenyGrantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Grant

    func revokeGrant(
      request: RevokeGrantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
