// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// This API allows customers to manage temporary, request based privileged
/// access to their resources.
///
/// It defines the following resource model:
///
/// * A collection of `Entitlement` resources. An entitlement allows configuring
///   (among other things):
///
///   * Some kind of privileged access that users can request.
///   * A set of users called _requesters_ who can request this access.
///   * A maximum duration for which the access can be requested.
///   * An optional approval workflow which must be satisfied before access is
///     granted.
///
/// * A collection of `Grant` resources. A grant is a request by a requester to
///   get the privileged access specified in an entitlement for some duration.
///
///   After the approval workflow as specified in the entitlement is satisfied,
///   the specified access is given to the requester. The access is automatically
///   taken back after the requested duration is over.
///
/// @Snippet(path: "PrivilegedAccessManagerQuickstart")
public final class PrivilegedAccessManagerClient: Clients.PrivilegedAccessManagerProtocol, Sendable
{
  let inner: any Clients.PrivilegedAccessManagerStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `PrivilegedAccessManagerClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.PrivilegedAccessManagerStub =
      try Clients.PrivilegedAccessManagerTransport(options)
    inner = Clients.PrivilegedAccessManagerRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.PrivilegedAccessManagerLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// `CheckOnboardingStatus` reports the onboarding status for a
  /// project/folder/organization. Any findings reported by this API need to be
  /// fixed before PAM can be used on the resource.
  ///
  /// @Snippet(path: "PrivilegedAccessManager_CheckOnboardingStatus")
  public func checkOnboardingStatus(
    request: CheckOnboardingStatusRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPrivilegedAccessManagerV1.CheckOnboardingStatusResponse {
    try await self.inner.checkOnboardingStatus(request: request, options: options)
  }

  /// Lists entitlements in a given project/folder/organization and location.
  ///
  /// @Snippet(path: "PrivilegedAccessManager_ListEntitlements")
  public func listEntitlements(
    request: ListEntitlementsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPrivilegedAccessManagerV1.ListEntitlementsResponse {
    try await self.inner.listEntitlements(request: request, options: options)
  }

  /// Lists entitlements in a given project/folder/organization and location.
  ///
  /// @Snippet(path: "PrivilegedAccessManager_ListEntitlements")
  public func listEntitlements(
    byItem: ListEntitlementsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Entitlement, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudPrivilegedAccessManagerV1.ListEntitlementsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listEntitlements(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// `SearchEntitlements` returns entitlements on which the caller has the
  /// specified access.
  ///
  /// @Snippet(path: "PrivilegedAccessManager_SearchEntitlements")
  public func searchEntitlements(
    request: SearchEntitlementsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPrivilegedAccessManagerV1.SearchEntitlementsResponse {
    try await self.inner.searchEntitlements(request: request, options: options)
  }

  /// `SearchEntitlements` returns entitlements on which the caller has the
  /// specified access.
  ///
  /// @Snippet(path: "PrivilegedAccessManager_SearchEntitlements")
  public func searchEntitlements(
    byItem: SearchEntitlementsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Entitlement, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudPrivilegedAccessManagerV1.SearchEntitlementsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.searchEntitlements(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single entitlement.
  ///
  /// @Snippet(path: "PrivilegedAccessManager_GetEntitlement")
  public func getEntitlement(
    request: GetEntitlementRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Entitlement {
    try await self.inner.getEntitlement(request: request, options: options)
  }

  /// Creates a new entitlement in a given project/folder/organization and
  /// location.
  ///
  /// @Snippet(path: "PrivilegedAccessManager_CreateEntitlement")
  public func createEntitlement(
    request: CreateEntitlementRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createEntitlement(request: request, options: options)
  }

  /// Creates a new entitlement in a given project/folder/organization and
  /// location.
  ///
  /// @Snippet(path: "PrivilegedAccessManager_CreateEntitlement")
  public func createEntitlement(
    withPolling: CreateEntitlementRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Entitlement> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Entitlement>.State in
      return try op._extractStatus(Entitlement.self)
    }
    let rawOp = try await self.createEntitlement(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Entitlement>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single entitlement. This method can only be called when there
  /// are no in-progress (`ACTIVE`/`ACTIVATING`/`REVOKING`) grants under the
  /// entitlement.
  ///
  /// @Snippet(path: "PrivilegedAccessManager_DeleteEntitlement")
  public func deleteEntitlement(
    request: DeleteEntitlementRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteEntitlement(request: request, options: options)
  }

  /// Deletes a single entitlement. This method can only be called when there
  /// are no in-progress (`ACTIVE`/`ACTIVATING`/`REVOKING`) grants under the
  /// entitlement.
  ///
  /// @Snippet(path: "PrivilegedAccessManager_DeleteEntitlement")
  public func deleteEntitlement(
    withPolling: DeleteEntitlementRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Entitlement> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Entitlement>.State in
      return try op._extractStatus(Entitlement.self)
    }
    let rawOp = try await self.deleteEntitlement(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Entitlement>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the entitlement specified in the request. Updated fields in the
  /// entitlement need to be specified in an update mask. The changes made to an
  /// entitlement are applicable only on future grants of the entitlement.
  /// However, if new approvers are added or existing approvers are removed from
  /// the approval workflow, the changes are effective on existing grants.
  ///
  /// The following fields are not supported for updates:
  ///
  ///  * All immutable fields
  ///  * Entitlement name
  ///  * Resource name
  ///  * Resource type
  ///  * Adding an approval workflow in an entitlement which previously had no
  ///    approval workflow.
  ///  * Deleting the approval workflow from an entitlement.
  ///  * Adding or deleting a step in the approval workflow (only one step is
  ///    supported)
  ///
  /// Note that updates are allowed on the list of approvers in an approval
  /// workflow step.
  ///
  /// @Snippet(path: "PrivilegedAccessManager_UpdateEntitlement")
  public func updateEntitlement(
    request: UpdateEntitlementRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateEntitlement(request: request, options: options)
  }

  /// Updates the entitlement specified in the request. Updated fields in the
  /// entitlement need to be specified in an update mask. The changes made to an
  /// entitlement are applicable only on future grants of the entitlement.
  /// However, if new approvers are added or existing approvers are removed from
  /// the approval workflow, the changes are effective on existing grants.
  ///
  /// The following fields are not supported for updates:
  ///
  ///  * All immutable fields
  ///  * Entitlement name
  ///  * Resource name
  ///  * Resource type
  ///  * Adding an approval workflow in an entitlement which previously had no
  ///    approval workflow.
  ///  * Deleting the approval workflow from an entitlement.
  ///  * Adding or deleting a step in the approval workflow (only one step is
  ///    supported)
  ///
  /// Note that updates are allowed on the list of approvers in an approval
  /// workflow step.
  ///
  /// @Snippet(path: "PrivilegedAccessManager_UpdateEntitlement")
  public func updateEntitlement(
    withPolling: UpdateEntitlementRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Entitlement> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Entitlement>.State in
      return try op._extractStatus(Entitlement.self)
    }
    let rawOp = try await self.updateEntitlement(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Entitlement>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists grants for a given entitlement.
  ///
  /// @Snippet(path: "PrivilegedAccessManager_ListGrants")
  public func listGrants(
    request: ListGrantsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPrivilegedAccessManagerV1.ListGrantsResponse {
    try await self.inner.listGrants(request: request, options: options)
  }

  /// Lists grants for a given entitlement.
  ///
  /// @Snippet(path: "PrivilegedAccessManager_ListGrants")
  public func listGrants(
    byItem: ListGrantsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Grant, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudPrivilegedAccessManagerV1.ListGrantsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listGrants(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// `SearchGrants` returns grants that are related to the calling user in the
  /// specified way.
  ///
  /// @Snippet(path: "PrivilegedAccessManager_SearchGrants")
  public func searchGrants(
    request: SearchGrantsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPrivilegedAccessManagerV1.SearchGrantsResponse {
    try await self.inner.searchGrants(request: request, options: options)
  }

  /// `SearchGrants` returns grants that are related to the calling user in the
  /// specified way.
  ///
  /// @Snippet(path: "PrivilegedAccessManager_SearchGrants")
  public func searchGrants(
    byItem: SearchGrantsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Grant, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudPrivilegedAccessManagerV1.SearchGrantsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.searchGrants(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Get details of a single grant.
  ///
  /// @Snippet(path: "PrivilegedAccessManager_GetGrant")
  public func getGrant(
    request: GetGrantRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Grant {
    try await self.inner.getGrant(request: request, options: options)
  }

  /// Creates a new grant in a given project/folder/organization and
  /// location.
  ///
  /// @Snippet(path: "PrivilegedAccessManager_CreateGrant")
  public func createGrant(
    request: CreateGrantRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Grant {
    try await self.inner.createGrant(request: request, options: options)
  }

  /// `ApproveGrant` is used to approve a grant. This method can only be called
  /// on a grant when it's in the `APPROVAL_AWAITED` state. This operation can't
  /// be undone.
  ///
  /// @Snippet(path: "PrivilegedAccessManager_ApproveGrant")
  public func approveGrant(
    request: ApproveGrantRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Grant {
    try await self.inner.approveGrant(request: request, options: options)
  }

  /// `DenyGrant` is used to deny a grant. This method can only be called on a
  /// grant when it's in the `APPROVAL_AWAITED` state. This operation can't be
  /// undone.
  ///
  /// @Snippet(path: "PrivilegedAccessManager_DenyGrant")
  public func denyGrant(
    request: DenyGrantRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Grant {
    try await self.inner.denyGrant(request: request, options: options)
  }

  /// `RevokeGrant` is used to immediately revoke access for a grant. This method
  /// can be called when the grant is in a non-terminal state.
  ///
  /// @Snippet(path: "PrivilegedAccessManager_RevokeGrant")
  public func revokeGrant(
    request: RevokeGrantRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.revokeGrant(request: request, options: options)
  }

  /// `RevokeGrant` is used to immediately revoke access for a grant. This method
  /// can be called when the grant is in a non-terminal state.
  ///
  /// @Snippet(path: "PrivilegedAccessManager_RevokeGrant")
  public func revokeGrant(
    withPolling: RevokeGrantRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Grant> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Grant>.State
      in
      return try op._extractStatus(Grant.self)
    }
    let rawOp = try await self.revokeGrant(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Grant>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "PrivilegedAccessManager_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "PrivilegedAccessManager_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "PrivilegedAccessManager_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "PrivilegedAccessManager_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "PrivilegedAccessManager_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "PrivilegedAccessManager_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "PrivilegedAccessManager_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `PrivilegedAccessManagerClient`.
  ///
  /// To mock `PrivilegedAccessManagerClient` change your functions to receive
  /// `some PrivilegedAccessManagerProtocol` or `any PrivilegedAccessManagerProtocol`
  /// and pass a mock implementation in your tests.
  public protocol PrivilegedAccessManagerProtocol {
    /// See `PrivilegedAccessManagerClient.checkOnboardingStatus`.
    func checkOnboardingStatus(request: CheckOnboardingStatusRequest) async throws
      -> GoogleCloudPrivilegedAccessManagerV1.CheckOnboardingStatusResponse

    /// See `PrivilegedAccessManagerClient.listEntitlements`.
    func listEntitlements(request: ListEntitlementsRequest) async throws
      -> GoogleCloudPrivilegedAccessManagerV1.ListEntitlementsResponse

    /// See `PrivilegedAccessManagerClient.listEntitlements`.
    func listEntitlements(
      byItem: ListEntitlementsRequest
    ) throws -> any AsyncSequence<Entitlement, Swift.Error>

    /// See `PrivilegedAccessManagerClient.listEntitlements`.
    func listEntitlements(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Entitlement, Swift.Error>

    /// See `PrivilegedAccessManagerClient.searchEntitlements`.
    func searchEntitlements(request: SearchEntitlementsRequest) async throws
      -> GoogleCloudPrivilegedAccessManagerV1.SearchEntitlementsResponse

    /// See `PrivilegedAccessManagerClient.searchEntitlements`.
    func searchEntitlements(
      byItem: SearchEntitlementsRequest
    ) throws -> any AsyncSequence<Entitlement, Swift.Error>

    /// See `PrivilegedAccessManagerClient.getEntitlement`.
    func getEntitlement(request: GetEntitlementRequest) async throws
      -> GoogleCloudPrivilegedAccessManagerV1.Entitlement

    /// See `PrivilegedAccessManagerClient.getEntitlement`.
    func getEntitlement(
      name: Swift.String,
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Entitlement

    /// See `PrivilegedAccessManagerClient.createEntitlement`.
    func createEntitlement(request: CreateEntitlementRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `PrivilegedAccessManagerClient.createEntitlement`.
    func createEntitlement(withPolling: CreateEntitlementRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Entitlement>

    /// See `PrivilegedAccessManagerClient.createEntitlement`.
    func createEntitlement(
      parent: Swift.String,
      entitlement: Entitlement?,
      entitlementId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Entitlement>

    /// See `PrivilegedAccessManagerClient.deleteEntitlement`.
    func deleteEntitlement(request: DeleteEntitlementRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `PrivilegedAccessManagerClient.deleteEntitlement`.
    func deleteEntitlement(withPolling: DeleteEntitlementRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Entitlement>

    /// See `PrivilegedAccessManagerClient.deleteEntitlement`.
    func deleteEntitlement(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Entitlement>

    /// See `PrivilegedAccessManagerClient.updateEntitlement`.
    func updateEntitlement(request: UpdateEntitlementRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `PrivilegedAccessManagerClient.updateEntitlement`.
    func updateEntitlement(withPolling: UpdateEntitlementRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Entitlement>

    /// See `PrivilegedAccessManagerClient.updateEntitlement`.
    func updateEntitlement(
      entitlement: Entitlement?,
      updateMask: GoogleCloudWKT.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Entitlement>

    /// See `PrivilegedAccessManagerClient.listGrants`.
    func listGrants(request: ListGrantsRequest) async throws
      -> GoogleCloudPrivilegedAccessManagerV1.ListGrantsResponse

    /// See `PrivilegedAccessManagerClient.listGrants`.
    func listGrants(
      byItem: ListGrantsRequest
    ) throws -> any AsyncSequence<Grant, Swift.Error>

    /// See `PrivilegedAccessManagerClient.listGrants`.
    func listGrants(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Grant, Swift.Error>

    /// See `PrivilegedAccessManagerClient.searchGrants`.
    func searchGrants(request: SearchGrantsRequest) async throws
      -> GoogleCloudPrivilegedAccessManagerV1.SearchGrantsResponse

    /// See `PrivilegedAccessManagerClient.searchGrants`.
    func searchGrants(
      byItem: SearchGrantsRequest
    ) throws -> any AsyncSequence<Grant, Swift.Error>

    /// See `PrivilegedAccessManagerClient.getGrant`.
    func getGrant(request: GetGrantRequest) async throws
      -> GoogleCloudPrivilegedAccessManagerV1.Grant

    /// See `PrivilegedAccessManagerClient.getGrant`.
    func getGrant(
      name: Swift.String,
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Grant

    /// See `PrivilegedAccessManagerClient.createGrant`.
    func createGrant(request: CreateGrantRequest) async throws
      -> GoogleCloudPrivilegedAccessManagerV1.Grant

    /// See `PrivilegedAccessManagerClient.createGrant`.
    func createGrant(
      parent: Swift.String,
      grant: Grant?,
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Grant

    /// See `PrivilegedAccessManagerClient.approveGrant`.
    func approveGrant(request: ApproveGrantRequest) async throws
      -> GoogleCloudPrivilegedAccessManagerV1.Grant

    /// See `PrivilegedAccessManagerClient.denyGrant`.
    func denyGrant(request: DenyGrantRequest) async throws
      -> GoogleCloudPrivilegedAccessManagerV1.Grant

    /// See `PrivilegedAccessManagerClient.revokeGrant`.
    func revokeGrant(request: RevokeGrantRequest) async throws -> GoogleLongRunning.Operation

    /// See `PrivilegedAccessManagerClient.revokeGrant`.
    func revokeGrant(withPolling: RevokeGrantRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Grant>

    /// See `PrivilegedAccessManagerClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `PrivilegedAccessManagerClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `PrivilegedAccessManagerClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `PrivilegedAccessManagerClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `PrivilegedAccessManagerClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `PrivilegedAccessManagerClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `PrivilegedAccessManagerClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `PrivilegedAccessManagerClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `PrivilegedAccessManagerClient.checkOnboardingStatus`.
    func checkOnboardingStatus(
      request: CheckOnboardingStatusRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.CheckOnboardingStatusResponse

    /// See `PrivilegedAccessManagerClient.listEntitlements`.
    func listEntitlements(
      request: ListEntitlementsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.ListEntitlementsResponse

    /// See `PrivilegedAccessManagerClient.listEntitlements`.
    func listEntitlements(
      byItem: ListEntitlementsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Entitlement, Swift.Error>

    /// See `PrivilegedAccessManagerClient.searchEntitlements`.
    func searchEntitlements(
      request: SearchEntitlementsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.SearchEntitlementsResponse

    /// See `PrivilegedAccessManagerClient.searchEntitlements`.
    func searchEntitlements(
      byItem: SearchEntitlementsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Entitlement, Swift.Error>

    /// See `PrivilegedAccessManagerClient.getEntitlement`.
    func getEntitlement(
      request: GetEntitlementRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Entitlement

    /// See `PrivilegedAccessManagerClient.createEntitlement`.
    func createEntitlement(
      request: CreateEntitlementRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `PrivilegedAccessManagerClient.createEntitlement`.
    func createEntitlement(
      withPolling: CreateEntitlementRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Entitlement>

    /// See `PrivilegedAccessManagerClient.deleteEntitlement`.
    func deleteEntitlement(
      request: DeleteEntitlementRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `PrivilegedAccessManagerClient.deleteEntitlement`.
    func deleteEntitlement(
      withPolling: DeleteEntitlementRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Entitlement>

    /// See `PrivilegedAccessManagerClient.updateEntitlement`.
    func updateEntitlement(
      request: UpdateEntitlementRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `PrivilegedAccessManagerClient.updateEntitlement`.
    func updateEntitlement(
      withPolling: UpdateEntitlementRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Entitlement>

    /// See `PrivilegedAccessManagerClient.listGrants`.
    func listGrants(
      request: ListGrantsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.ListGrantsResponse

    /// See `PrivilegedAccessManagerClient.listGrants`.
    func listGrants(
      byItem: ListGrantsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Grant, Swift.Error>

    /// See `PrivilegedAccessManagerClient.searchGrants`.
    func searchGrants(
      request: SearchGrantsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.SearchGrantsResponse

    /// See `PrivilegedAccessManagerClient.searchGrants`.
    func searchGrants(
      byItem: SearchGrantsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Grant, Swift.Error>

    /// See `PrivilegedAccessManagerClient.getGrant`.
    func getGrant(
      request: GetGrantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Grant

    /// See `PrivilegedAccessManagerClient.createGrant`.
    func createGrant(
      request: CreateGrantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Grant

    /// See `PrivilegedAccessManagerClient.approveGrant`.
    func approveGrant(
      request: ApproveGrantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Grant

    /// See `PrivilegedAccessManagerClient.denyGrant`.
    func denyGrant(
      request: DenyGrantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Grant

    /// See `PrivilegedAccessManagerClient.revokeGrant`.
    func revokeGrant(
      request: RevokeGrantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `PrivilegedAccessManagerClient.revokeGrant`.
    func revokeGrant(
      withPolling: RevokeGrantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Grant>

    /// See `PrivilegedAccessManagerClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `PrivilegedAccessManagerClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `PrivilegedAccessManagerClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `PrivilegedAccessManagerClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `PrivilegedAccessManagerClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `PrivilegedAccessManagerClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.PrivilegedAccessManagerProtocol {
  public func checkOnboardingStatus(request: CheckOnboardingStatusRequest) async throws
    -> GoogleCloudPrivilegedAccessManagerV1.CheckOnboardingStatusResponse
  {
    try await self.checkOnboardingStatus(request: request, options: .init())
  }

  public func checkOnboardingStatus(
    request: CheckOnboardingStatusRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPrivilegedAccessManagerV1.CheckOnboardingStatusResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listEntitlements(request: ListEntitlementsRequest) async throws
    -> GoogleCloudPrivilegedAccessManagerV1.ListEntitlementsResponse
  {
    try await self.listEntitlements(request: request, options: .init())
  }

  public func listEntitlements(
    request: ListEntitlementsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPrivilegedAccessManagerV1.ListEntitlementsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listEntitlements(
    byItem: ListEntitlementsRequest
  ) throws -> any AsyncSequence<Entitlement, Swift.Error> {
    try self.listEntitlements(byItem: byItem, options: .init())
  }

  public func listEntitlements(
    byItem: ListEntitlementsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Entitlement, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudPrivilegedAccessManagerV1.ListEntitlementsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listEntitlements(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Entitlement, Swift.Error> {
    let request = ListEntitlementsRequest().with {
      $0.parent = parent
    }
    return try self.listEntitlements(byItem: request)
  }

  public func searchEntitlements(request: SearchEntitlementsRequest) async throws
    -> GoogleCloudPrivilegedAccessManagerV1.SearchEntitlementsResponse
  {
    try await self.searchEntitlements(request: request, options: .init())
  }

  public func searchEntitlements(
    request: SearchEntitlementsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPrivilegedAccessManagerV1.SearchEntitlementsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func searchEntitlements(
    byItem: SearchEntitlementsRequest
  ) throws -> any AsyncSequence<Entitlement, Swift.Error> {
    try self.searchEntitlements(byItem: byItem, options: .init())
  }

  public func searchEntitlements(
    byItem: SearchEntitlementsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Entitlement, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudPrivilegedAccessManagerV1.SearchEntitlementsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getEntitlement(request: GetEntitlementRequest) async throws
    -> GoogleCloudPrivilegedAccessManagerV1.Entitlement
  {
    try await self.getEntitlement(request: request, options: .init())
  }

  public func getEntitlement(
    request: GetEntitlementRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Entitlement {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getEntitlement(
    name: Swift.String,
  ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Entitlement {
    let request = GetEntitlementRequest().with {
      $0.name = name
    }
    return try await self.getEntitlement(request: request)
  }

  public func createEntitlement(request: CreateEntitlementRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createEntitlement(request: request, options: .init())
  }

  public func createEntitlement(
    request: CreateEntitlementRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createEntitlement(withPolling: CreateEntitlementRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Entitlement>
  {
    try await self.createEntitlement(withPolling: withPolling, options: .init())
  }

  public func createEntitlement(
    withPolling: CreateEntitlementRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Entitlement> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Entitlement>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createEntitlement(
    parent: Swift.String,
    entitlement: Entitlement?,
    entitlementId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Entitlement> {
    let request = CreateEntitlementRequest().with {
      $0.parent = parent
      $0.entitlement = entitlement
      $0.entitlementId = entitlementId
    }
    return try await self.createEntitlement(withPolling: request)
  }

  public func deleteEntitlement(request: DeleteEntitlementRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteEntitlement(request: request, options: .init())
  }

  public func deleteEntitlement(
    request: DeleteEntitlementRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteEntitlement(withPolling: DeleteEntitlementRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Entitlement>
  {
    try await self.deleteEntitlement(withPolling: withPolling, options: .init())
  }

  public func deleteEntitlement(
    withPolling: DeleteEntitlementRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Entitlement> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Entitlement>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteEntitlement(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Entitlement> {
    let request = DeleteEntitlementRequest().with {
      $0.name = name
    }
    return try await self.deleteEntitlement(withPolling: request)
  }

  public func updateEntitlement(request: UpdateEntitlementRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateEntitlement(request: request, options: .init())
  }

  public func updateEntitlement(
    request: UpdateEntitlementRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateEntitlement(withPolling: UpdateEntitlementRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Entitlement>
  {
    try await self.updateEntitlement(withPolling: withPolling, options: .init())
  }

  public func updateEntitlement(
    withPolling: UpdateEntitlementRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Entitlement> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Entitlement>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateEntitlement(
    entitlement: Entitlement?,
    updateMask: GoogleCloudWKT.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Entitlement> {
    let request = UpdateEntitlementRequest().with {
      $0.entitlement = entitlement
      $0.updateMask = updateMask
    }
    return try await self.updateEntitlement(withPolling: request)
  }

  public func listGrants(request: ListGrantsRequest) async throws
    -> GoogleCloudPrivilegedAccessManagerV1.ListGrantsResponse
  {
    try await self.listGrants(request: request, options: .init())
  }

  public func listGrants(
    request: ListGrantsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPrivilegedAccessManagerV1.ListGrantsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listGrants(
    byItem: ListGrantsRequest
  ) throws -> any AsyncSequence<Grant, Swift.Error> {
    try self.listGrants(byItem: byItem, options: .init())
  }

  public func listGrants(
    byItem: ListGrantsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Grant, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudPrivilegedAccessManagerV1.ListGrantsResponse
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listGrants(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Grant, Swift.Error> {
    let request = ListGrantsRequest().with {
      $0.parent = parent
    }
    return try self.listGrants(byItem: request)
  }

  public func searchGrants(request: SearchGrantsRequest) async throws
    -> GoogleCloudPrivilegedAccessManagerV1.SearchGrantsResponse
  {
    try await self.searchGrants(request: request, options: .init())
  }

  public func searchGrants(
    request: SearchGrantsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPrivilegedAccessManagerV1.SearchGrantsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func searchGrants(
    byItem: SearchGrantsRequest
  ) throws -> any AsyncSequence<Grant, Swift.Error> {
    try self.searchGrants(byItem: byItem, options: .init())
  }

  public func searchGrants(
    byItem: SearchGrantsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Grant, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudPrivilegedAccessManagerV1.SearchGrantsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getGrant(request: GetGrantRequest) async throws
    -> GoogleCloudPrivilegedAccessManagerV1.Grant
  {
    try await self.getGrant(request: request, options: .init())
  }

  public func getGrant(
    request: GetGrantRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Grant {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getGrant(
    name: Swift.String,
  ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Grant {
    let request = GetGrantRequest().with {
      $0.name = name
    }
    return try await self.getGrant(request: request)
  }

  public func createGrant(request: CreateGrantRequest) async throws
    -> GoogleCloudPrivilegedAccessManagerV1.Grant
  {
    try await self.createGrant(request: request, options: .init())
  }

  public func createGrant(
    request: CreateGrantRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Grant {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createGrant(
    parent: Swift.String,
    grant: Grant?,
  ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Grant {
    let request = CreateGrantRequest().with {
      $0.parent = parent
      $0.grant = grant
    }
    return try await self.createGrant(request: request)
  }

  public func approveGrant(request: ApproveGrantRequest) async throws
    -> GoogleCloudPrivilegedAccessManagerV1.Grant
  {
    try await self.approveGrant(request: request, options: .init())
  }

  public func approveGrant(
    request: ApproveGrantRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Grant {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func denyGrant(request: DenyGrantRequest) async throws
    -> GoogleCloudPrivilegedAccessManagerV1.Grant
  {
    try await self.denyGrant(request: request, options: .init())
  }

  public func denyGrant(
    request: DenyGrantRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPrivilegedAccessManagerV1.Grant {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func revokeGrant(request: RevokeGrantRequest) async throws -> GoogleLongRunning.Operation {
    try await self.revokeGrant(request: request, options: .init())
  }

  public func revokeGrant(
    request: RevokeGrantRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func revokeGrant(withPolling: RevokeGrantRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Grant>
  {
    try await self.revokeGrant(withPolling: withPolling, options: .init())
  }

  public func revokeGrant(
    withPolling: RevokeGrantRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Grant> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Grant>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }
}
