// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Message for updating an entitlement.
public struct UpdateEntitlementRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The entitlement resource that is updated.
  public var entitlement: Entitlement? = nil

  /// Required. The list of fields to update. A field is overwritten if, and only
  /// if, it is in the mask. Any immutable fields set in the mask are ignored by
  /// the server. Repeated fields and map fields are only allowed in the last
  /// position of a `paths` string and overwrite the existing values. Hence an
  /// update to a repeated field or a map should contain the entire list of
  /// values. The fields specified in the update_mask are relative to the
  /// resource and not to the request.
  /// (e.g. `MaxRequestDuration`; *not* `entitlement.MaxRequestDuration`)
  /// A value of '*' for this field refers to full replacement of the resource.
  public var updateMask: GoogleCloudWkt.FieldMask? = nil

  /// Initialize a new instance of `UpdateEntitlementRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateEntitlementRequest().with { $0.entitlement = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.privilegedaccessmanager.v1.UpdateEntitlementRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
